### ISSUE TITLE
Support for links?

### ISSUE THREAD

**Issue by tartavull** [charmbracelet/wish#148]
There is a standard called OSC 8 that some modern terminal emulators use to enable clickable links. This is not universally supported, but it does work in a number of popular terminals like iTerm2, GNOME Terminal, mintty, and others.

Here is an example of how you can output a hyperlink in a terminal using this method:

```bash
echo -e '\e]8;;http://example.com\aThis is a link\e]8;;\a'
```
When you run this command in a terminal that supports OSC 8, it will output the text "This is a link", and you can click on it to open http://example.com/ in your web browser.

While my terminal supports OSC 8, the link is not clickable when output with Wish.
```go
fmt.Fprintf(&b, "%s\n", "\033]8;;http://example.com\aThis is a link\033]8;;\a")
```
Do you happen to know if this is a limitation of ssh or wish or something else?

Given that I can ssh into a machine and use the echo command and it produces a clickable link, and I can also write a simple program in Go that also produces the clickable link I'm inclined to believe that it is a limitation of wish, isn't it?
```go
package main

import "fmt"

func main() {
    fmt.Println("\033]8;;http://example.com\aThis is a link\033]8;;\a")
}
```

**Comment by tartavull** [comment]
@caarlos0 Do you happen to know how to enable links?

**Comment by caarlos0** [comment]
@tartavull I'll investigate this week

**Comment by caarlos0** [comment]
Just tested it here with

```golang
wish.Println(session, "\033]8;;http://example.com\aThis is a link\033]8;;\a")
```

and it works. 🤔

FWIW: it seems to not work inside tmux, with or without ssh and/or wish.

**Comment by tartavull** [comment]
I wonder why it doesn't work in my application, maybe related to bubblezone or something alike.

Thank you!
