### ISSUE TITLE
hooks

### ISSUE THREAD

**Issue by till** [charmbracelet/wish#150]
Hi 👋🏼  — any chance you would consider supporting git hooks in the git middleware? I saw soft-serve has them, but it does too many other things I would have to turn off, etc.. And this server has been a pleasure so far. I think the only thing I am missing is being able to override `ensureRepo()` somehow to add the hooks?

**Comment by aymanbagabas** [comment]
Hi @till, githooks are essentially just shell scripts the git binary run on fetch/push events. You could have a separate Wish middleware to create the hook scripts for each repository. Look at Soft Serve [`hooks.go`](https://github.com/charmbracelet/soft-serve/blob/main/server/hooks/hooks.go#L121) for an example of writing git server hooks.

**Comment by aymanbagabas** [comment]
You could create a `hooksMiddleware` and build a `ensureHooks` to ensure you have the hooks in place after pushing.

Take a look at this:

```go
s, err := wish.NewServer(
  wish.WithMiddleware(
        // Run hooksMiddleware _after_ the git middleware
        hooksMiddleware(repoDir),
	gm.Middleware(repoDir, a),
	lm.Middleware(),
  ),
)

...

func hooksMiddleware(repoDir string) wish.Middleware {
  return func(sh ssh.Handler) ssh.Handler {
    return func(s ssh.Session) {
      cmd := s.Command()
      if len(cmd) == 2 && cmd[0] == "git-receive-pack" {
        // Ensure repo hooks exist
        _ = ensureHooks(repoDir, cmd[1])
      }
    }
  }
}

...

func ensureHooks(dir string, repo string) error {
  // create repo hooks
  if _, err := os.Stat(filepath.Join(dir, repo, "hooks", "update")); err != nil {
    // update hook doesn't exist, create?
    // make sure the hook scripts are executable
  }
  // handle other hooks
}
```

**Comment by till** [comment]
@aymanbagabas makes sense, would you take a PR to make ensureRepo public to open it a bit up? Otherwise if not, I understand.

**Comment by caarlos0** [comment]
I think it would be ok, @till
