### ISSUE TITLE
banner instead of comment?

### ISSUE THREAD

**Issue by dezren39** [charmbracelet/wish#205]
is it possible to make a banner middleware? i'm just gonna have my tea middleware output a banner instead but i had tried to figure out a way to make a generic middleware that is basically comment but at the beginning, couldn't figure it out! kind of feels like it would need to be a (ssh.Option) wish.WithBanner(string) function like outside middleware so the server can just output first. basically for showing a motd and standard banner about terms of service type stuff. later i'll probably build a fancier manual auth for users where they, idk, hit 'Y' or 'Enter' to accept or Ctrl+c to decline, but i'd like to have an easy way to throw a generic header for simpler cases or maybe when user is recognized as already having accepted.

**Comment by caarlos0** [comment]
hey, I opened the needed PRs to add this functionality. 

thanks for the issue 🙏


see #210
