### ISSUE TITLE
WithCustomAuth

### ISSUE THREAD

**Issue by dezren39** [charmbracelet/wish#208]
hello!

so i want to accept any session, but then run a custom function that is basically WithCustomAuth `func(h ssh.Handler) bool`, or a custom handler that only has a context like `func(ctx Context) bool` or both (context would work especially well if i could guarantee customAuth always runs and is last, so i could maybe pass data through ctx.Permissions from the pk/interactive/pw handlers and then handle the last part there.

maybe this isn't the right way to handle this. right now i have a middleware where i have something like
```
func(h ssh.Handler) ssh.Handler {
	return func(s ssh.Session) {
		authorizedKey := gossh.MarshalAuthorizedKey(s.PublicKey())
...
```
and intend to allow it to handle password/interactive auth too. i have each withAuth before this, so 'all auth' is accepted and then i handle the 'real auth' here. my concern is that as a middleware i don't know that i have it in the right order. so i have ssh logic in this middleware, but i also have the scp middleware on the server. my belief is that the scp middleware doesn't run the ssh handler above, or rather doesn't prevent scp i can't use it as auth. so i need to split my ssh handler into the auth portion and the real ssh stuff, then i need a way to run custom auth which is generic and functions for all the varied middleware? does that make sense? idk. I can just replicate the logic for each of the 3 auth paths? maybe its just a matter of how i order the middleware list and it's all covered already?

**Comment by dezren39** [comment]
Related, I'd like to still accept without auth even if I accept authenticated connections. Is that possible? Or will I need to tell users to submit empty passwords at least? Or is an empty password the default if one isn't provided?
```
When both PasswordHandler and PublicKeyHandler are nil, no client authentication is performed.
```

**Comment by stan-dot** [comment]
hey @dezren39 how did it resolve?

would it be possible to connect with open policy agent?

**Comment by dezren39** [comment]
I resolved this through changing how I used wish, I believe you could hook open policy up to wish but don't have a good example for you to look at for that. Only one auth type is ultimately used per connection

**Comment by stan-dot** [comment]
thanks!
