### ISSUE TITLE
ratelimiter how does it work?

### ISSUE THREAD

**Issue by dezren39** [charmbracelet/wish#220]
I'm sorry I don't understand what a token is or a request? Is it like amount of data? Or amount of commands? Or ssh connections? I understand the lru and the ip address part, and conceptually the token thing, but I don't understand how to control this interface or what it exactly means. I tried looking but couldn't find out.

**Comment by caarlos0** [comment]
hey!

the provided rate limit implementation limits the amount of connections a source can make in X amount of time.

Docs should be better on this though, will improve them.

Thanks for the issue 🙏
