### ISSUE TITLE
scp limited fs

### ISSUE THREAD

**Issue by dezren39** [charmbracelet/wish#221]
i wish i could make like, an fs with a limited file system size for use with scp.

like, using ratelimiter for bandwidth/burst related limiting, but something that would let me provide a directory and they can put as much as they want until the dir (and anything in it) is more than limit amount. if a put would be more than amount then error.

is there a simple way to make this? so that users can scp, idk, up to 2gb, but any more breaks

**Comment by caarlos0** [comment]
You'll probably have to implemente a `scp.Handler` decorating `scp.FileSystemHandler` and dealing with all that in the `Write` method... something like:

```go
package foo 

// ...

type limitedHandler struct {
	scp.Handler
}

func (h limitedHandler) Write(s ssh.Session, entry *scp.FileEntry) (int64, error) {
	// check disk usage...
	return h.Handler.Write(s, entry)
}

func main() {
	handler := limitedHandler{scp.NewFileSystemHandler("./examples/scp/testdata")}
        // ...
}
```

Hope that helps :)

**Comment by dezren39** [comment]
ahh that makes sense! thank you
