### ISSUE TITLE
Directory Traversal

### ISSUE THREAD

**Issue by zachhanson94** [charmbracelet/wish#23]
Repo paths are not properly sanitized so users can access repos outside the designated repo dir.

Users with read access will be able to access repos outside the directory, and users with write permissions have the ability to write outside that directory as well. 

A quick example that sort of demonstrates whats happening is just to run 
```sh
git clone 'ssh://git.charm.sh/soft-serve/../glow'
```
That example doesnt demonstrate reading outside the repo directory (because I dont know where there may be repos on that server) but it does show that it walks the directory path just fine including the `..`. An attacker could implement some scanning logic to find other repos they arent supposed to have access to.

**Comment by toby** [comment]
Thank you for catching this. We'll get a fix in ASAP.

**Comment by toby** [comment]
Fixed and released in https://github.com/charmbracelet/wish/releases/tag/v0.1.2
