### ISSUE TITLE
Reverse tunnel example problem?

### ISSUE THREAD

**Issue by torntrousers** [charmbracelet/wish#242]
Hello, thanks so much for the forward example added in https://github.com/charmbracelet/wish/issues/191. I'm trying that but can't get it to work. Probbaly I'm misunderstanding something. Here's what i do:

I run the Wish simple example on port 23235 and test that works:
```
go run main.go
2024/02/25 13:44:26 INFO Starting SSH server host=localhost port=23235
2024/02/25 13:45:04 INFO tornt connect 127.0.0.1:55671 false [] xterm-256color 94 6
2024/02/25 13:45:04 INFO 127.0.0.1:55671 disconnect 0s
```
```
ssh localhost -p 23235
Hello, world!
Connection to localhost closed.
```
Then in another terminal window i run the Wish forward example:
```
go run main.go
2024/02/25 13:52:16 INFO Starting SSH server host=localhost port=23234
2024/02/25 13:52:26 INFO reverse port forwarding allowed host=localhost port=23236
```
and in another terminal window run the ssh tunnel:
```
ssh -N -R 23236:localhost:23235 -p 23234 localhost
```
then back at the ssh clinet window try to access the simple example via the tunnel using port 23236
```
ssh localhost -p 23236
kex_exchange_identification: read: Connection reset
Connection reset by 127.0.0.1 port 23236
```
which doesn't work and the connection is just reset.

What am i doing wrong?

**Comment by caarlos0** [comment]
I couldn't reproduce this issue here...

![CleanShot 2024-02-29 at 12 12 07@2x](https://github.com/charmbracelet/wish/assets/245435/9bee31aa-a5f3-4daa-9988-346c2783f9da)

**Comment by torntrousers** [comment]
Thanks @caarlos0 , interesting, i'll get another dev here to try too ...

**Comment by torntrousers** [comment]
A colleague confirmed it works fine for him too, so just me, and it turns out some Windows thing and it works fine in WSL for me too. Tried disabling Windows Defender firewall but that doesn't help, so don't know what the problem is. Don't use WIndows :) Thanks for looking @caarlos0  , i'll close this now.

**Comment by caarlos0** [comment]
ah, cool

thanks for getting back 🙏
