### ISSUE TITLE
Lipgloss doesn't detect background correctly when using wish

### ISSUE THREAD

**Issue by Aerochrome** [charmbracelet/wish#262]
**Describe the bug**
When using the `bubbletea.MakeRenderer` function,  `lipgloss.AdaptiveColor` and `lipgloss.Renderer.HasDarkBackground` always assume a black background, even though the terminal emulator from which i am using ssh has set a light background.

**Setup**
I'm running the wish example locally with `go run .` and also use a local terminal to access the ssh server.
It happens on Fedora 40 and MacOS with Gnome Terminal, iTerm2 and the standard mac terminal (all using zsh).

**To Reproduce**
1. Use [the bubbletea example](https://github.com/charmbracelet/wish/blob/main/examples/bubbletea/main.go) from the examples folder
2. Log HasDarkBackground using
`log.Info(renderer.HasDarkBackground())` in the `teaHandler` function right after creating the renderer using the bubbletea middleware
3. Create a new Lipgloss Style in the `teaHandler` function that uses the renderer created using the bubbletea middleware and `lipgloss.AdaptiveColor`
3.1 Render some text in the `View()` method of the model using the adaptive color lipgloss style

**Source Code**
I've created a simple one-file example in this gist:
https://gist.github.com/Aerochrome/5fd2af09f94eda22a0875068b8824acc

**Expected behavior**
When accessing with a terminal emulator **with a light background**, the second line should be colored **pink**.
When accessing **with a dark background**, the second line should be colored **red**.

**Screenshots**
Expectation:
<img width="1007" alt="gist_working" src="https://github.com/charmbracelet/wish/assets/24954031/0ab590ee-b3a7-4aa8-b5cc-1087c997764c">

Reality:
<img width="1006" alt="gist_not_working" src="https://github.com/charmbracelet/wish/assets/24954031/57534986-787a-4ee8-b507-a51af41774b9">

**Additional context**
DISCLAIMER: I am very new to TUIs and fairly new to go, so i'm not sure how useful my debugging findings actually are, but i want to share them nonetheless in case they're of any use.

I suspect that this issue might be related to a missing `Fd()` method implementation on the `ssh.Session` struct.
In the `bubbletea.newRenderer` method in [this file](https://github.com/charmbracelet/wish/blob/main/bubbletea/tea_unix.go#L32) a check is performed on whether the Slave pointer is nil. If so, it passes the session struct into `lipgloss.NewRenderer`.

While this struct has a `Write` method, it doesn't seem to implement the `Fd` method.

When adding a very rudimentary one like so, the background color check seems to work properly and produces a working example.

```go
func (sess *session) Fd() uintptr {
    return sess.pty.Slave.Fd() // Also works if sess.pty.Slave is nil
}
```

Of course, this doesn't account for `sess.pty.Slave` being nil (even though it produces a working example even if it is nil and i'm unsure why).

This suspicion is further confirmed by looking at an [older wish example](https://github.com/charmbracelet/lipgloss/blob/master/examples/ssh/main.go#L74) in the lipgloss repository, where a "helper" struct is created to pass into `lipgloss.Renderer.SetOutput` which also implements `Write` and `Fd`.
It also implements `Read`, though it doesn't seem to influence the outcome of a working example in my case.

So i've tried to use this helper struct, setting tty to pty.Slave and passing it into `bubbletea.MakeRenderer` like so, which produces a working example.

```go
sessionBridge := &sshOutput{
    Session: s,
    tty: pty.Slave,
}

renderer := bubbletea.MakeRenderer(sessionBridge)
```

Again, this also works if `pty.Slave` is nil.

It is also worth mentioning that in my case checking pty.Master and pty.Slave against nil in the `teaHandler` function returns true in both cases, even though `s.Pty()` returns true as third return value which i assume means that a PTY was accepted for this session.
I don't know if this is expected behavior in this specific case?

```go
log.Info(pty.Master == nil)
log.Info(pty.Slave == nil)
```

**Comment by adamdottv** [comment]
Also running into this! Happy to help if there's any opportunity to do so.

**Comment by caarlos0** [comment]
FWIW we're looking into it :) 

thanks for the detailed report

**Comment by Aerochrome** [comment]
Awesome, thank you!
Glad i was able to help :)

**Comment by caarlos0** [comment]
can you try on main?

**Comment by Aerochrome** [comment]
Sure!

I've tried to run the example i provided in the gist with the main branch of wish, however the issue still persists.

I've executed
- `go get github.com/charmbracelet/wish@main`
- `go mod tidy`

And i am now on version `v1.4.1-0.20240502183613-927ad4fbed5f` of wish.

Perhaps there is something else i'm missing?

**Comment by caarlos0** [comment]
afaik that should be it, can you share the project you're working on?

**Comment by Aerochrome** [comment]
Of course!

I've pushed my test project here: https://github.com/Aerochrome/charm-bg-test

**Comment by caarlos0** [comment]
right now it'll only work if you use allocatepty, I'm afraid

still looking into it though

**Comment by caarlos0** [comment]
awesome, thank you!
