### ISSUE TITLE
Wish SSH server crashes when some client abruptly closes the connection

### ISSUE THREAD

**Issue by k4kratik** [charmbracelet/wish#304]
**Describe the bug**
SSH server crashes whenever someone closes his/her terminal without quitting my app.

**Setup**
bubbletea v0.26.6
lipgloss v0.12.1
log v0.4.0
ssh v0.0.0-20240604154955-a40c6a0d028f
wish v1.4.1-0.20240715153630-7331818233ba

**To Reproduce**
1. connect to wish server
2. quit the terminal, without the exiting the app 

**Expected behavior**
It should not crash my ssh server.

**Screenshots**
![image](https://github.com/user-attachments/assets/095dbc9d-a828-46ec-8329-3b73d7e55989)

**Additional context**
on my virtual machine - I am using `screen` command to run wish server in background. 

Appreciate your help to fix this. Thanks.

**Comment by caarlos0** [comment]
can't repro.. can you share the smallest possible reproducible?

**Comment by bashbunni** [comment]
Hey @k4kratik please let us know if you have an example to reproduce this and I will reopen this issue, otherwise there isn't anything we can do to debug this. If anyone else has this same issue, please don't be shy to include steps to reproduce as well 🙏
