### ISSUE TITLE
New release needed to fix linux build

### ISSUE THREAD

**Issue by shaunco** [charmbracelet/wish#328]
**Describe the bug**
#311 changed from `github.com/charmbracelet/x/exp/term/input` to `github.com/charmbracelet/x/input` and now when I do a go build on linux, I get:
```
# github.com/charmbracelet/x/input
Error: ../../../go/pkg/mod/github.com/charmbracelet/x/input@v0.1.3/kitty.go:30:16: undefined: ansi.KittyReportAllKeys
```

This was fixed last week in https://github.com/charmbracelet/x/commit/61a8baf7aaddc8a7707ab7089a771c0742844fc7 and is in tag v0.2.0, which wish now points to in main (via https://github.com/charmbracelet/wish/commit/04eba59df9bf994d4140f8c41e770d069ec5608e ), however no new Wish release has been created since ... which means v1.4.2 is broken on linux.

Current workaround is to go back to v1.4.1

**Comment by caarlos0** [comment]
pushed v1.4.3

thanks!
