### ISSUE TITLE
localhost host doesn't resolve

### ISSUE THREAD

**Issue by HalanoSiblee** [charmbracelet/wish#338]
**Describe the bug**
localhost don't resolve on local ip I've to set the host manually to [192.168.1.x] so i can access it from my **public ip**

**Setup**
 - OS [archlinux]
 - Shell [fish]
 - Terminal Emulator [footclient]

**To Reproduce**
1. edit examples/simple/main.go
2. set port to 1024
3. ssh into your public ip [ssh x.x.x.x -p 1024]
4. ssh error

**Source Code**
```go
package main

import (
	"errors"
	"net"

	"github.com/charmbracelet/log"
	"github.com/charmbracelet/ssh"
	"github.com/charmbracelet/wish"
	"github.com/charmbracelet/wish/logging"
)

const (
	//host = "192.168.1.2" this for example will work.
	host = "localhost"
	port = "1024"
)

func main() {
	srv, err := wish.NewServer(
		wish.WithAddress(net.JoinHostPort(host, port)),
		wish.WithHostKeyPath(".ssh/id_ed25519"),
		wish.WithMiddleware(
			func(next ssh.Handler) ssh.Handler {
				return func(sess ssh.Session) {
					wish.Println(sess, "Hello, world!")
					next(sess)
				}
			},

			logging.Middleware(),
		),
	)
	if err != nil {
		log.Error("Could not start server", "error", err)
	}

	log.Info("Starting SSH server", "host", host, "port", port)
	if err = srv.ListenAndServe(); err != nil && !errors.Is(err, ssh.ErrServerClosed) {
		log.Error("Could not start server", "error", err)
	}
}

```
**Additional context**
I'm new to use this package and golang in general what did I miss or it's not a bug ?

**Comment by cslemes** [comment]
I'm using 0.0.0.0 on the host address as a wildcard host. I think that issue only occurs in a containerized environments, their localhost address resolves the DNS address as the IP of the server that hosting not a container localhost.

**Comment by HalanoSiblee** [comment]
Yeah, I get it, thanks for explaining this issue.
