### ISSUE TITLE
access to the `tea.Program` object

### ISSUE THREAD

**Issue by tgirod** [charmbracelet/wish#37]
I'm using `wish/bubbletea` to serve an application. I would like to use the method `Program.Send` so another part of the application can trigger a behaviour in the UI part, but I don't see how I can access the `tea.Program` object from the middleware.

**Comment by aymanbagabas** [comment]
@tgirod This is not currently possible with the bubbletea middleware. You could have your own middleware that has access to `tea.Program`. You can start by copying the current [bubbletea middleware](https://github.com/charmbracelet/wish/blob/main/bubbletea/tea.go#L37). Check out [Gambit middleware](https://github.com/maaslalani/gambit/blob/main/server/middleware.go) for an example.

**Comment by tgirod** [comment]
ok thanks! I'll try to do that.
