### ISSUE TITLE
document technical details of how Wish works

### ISSUE THREAD

**Issue by bashbunni** [charmbracelet/wish#42]
- [ ] #98
- [ ] #97
Basically go over the security concerns (we're using client-side not server-side, not attaching to daemon or shell)

**Comment by caarlos0** [comment]
@bashbunni what is the question about the blocking bit exactly? I can't quite remember it...

**Comment by bashbunni** [comment]
Hey @caarlos0 I can't remember :joy: You can close it. I'm sure someone will bring it to our attention again if it's something that should be added to our docs

**Comment by caarlos0** [comment]
sounds good hehe :D
