### ISSUE TITLE
Color issues when running the program under a systemd service

### ISSUE THREAD

**Issue by ynerant** [charmbracelet/wish#45]
Hi!

First, thanks for the great framework to make pretty terminal applications :)

I am currently working on a SSH application, using Wish and BubbleTea. In particular, I am using somewhere a colored progress bar. This is working well.

To manage and start properly my application, I am using a simple systemd service:

```
[Unit]
Description=My SSH application
After=network.target

[Service]
ExecStart=/path/to/binary
WorkingDirectory=/path/to/
Restart=on-failure
RestartSec=15s

[Install]
WantedBy=multi-user.target
```

And when I start this service, the SSH server is working well, but my terminal has no color, all is black and white. This happens only when I run the application through the systemd service. When I manually launch the binary, the colors are well displayed.

Do you know the origin of the issue, and how to fix it? I don't really want to keep my application opened in a tmux :D

**Comment by caarlos0** [comment]
are you using the bubbletea middleware? it does set a color profile, so that should work
https://github.com/charmbracelet/wish/blob/main/bubbletea/tea.go#L39

**Comment by bashbunni** [comment]
@aymanbagabas is this related to https://github.com/charmbracelet/bubbles/pull/152 do you think? Seems similar to a discussion I saw in the Slack :thinking:

**Comment by taigrr** [comment]
Related PR: https://github.com/muesli/termenv/pull/81

For an example of how to do autodetection of clients using wish and passing through to lipgloss, see github.com/taigrr/ssh-wars

Note that I forked and modified bubbles and lipgloss, so check my go.mod for replace directives

**Comment by caarlos0** [comment]
fwiw, for now you can force a profile: https://github.com/charmbracelet/wish/blob/v0.5.0/bubbletea/tea.go#L46

**Comment by caarlos0** [comment]
FWIW just to clarify: you can use `wish.MiddlewareWithColorProfile` to force a color profile for all sessions in the meantime.

**Comment by caarlos0** [comment]
this should be fixed by #197 (on `main`)

example: 0337c4bde860038975a372596036d628bf1c2dd9

**Comment by JohnCosta27** [comment]
I'm having a similar problem, but in my case what happens is:

Parts of the application render correctly with colours.
- When i use glamour to render markdown, and the list from bubbles, those no longer have colours.,
- Interestingly, they work when I'm not using systemd

If anyone has any idea, not sure where to go from here.

**Comment by taigrr** [comment]
are you shelling out? how is glamour invoked from your systemd service?
