### ISSUE TITLE
Max pseudo terminal limit in linux

### ISSUE THREAD

**Issue by oakes** [charmbracelet/wish#53]
Is it true that wish (or gliderlabs/ssh) allocates a new pty for each session? If so, doesn't that mean it's possible for the server to hit the max pty limit specified in `/proc/sys/kernel/pty/max` if there are a lot of concurrent connections? I imagine this would've happened when charm.sh hit the HN frontpage. I'm just wondering if this is something that is possible or if i'm misunderstanding how it works.

**Comment by caarlos0** [comment]
afaik, no.

I also tried this, running the `./examples/bubbletea/main.go` file, and sshing into it in multiple terminals, inspecting `/proc/sys/kernel/pty/nr` and then disconnecting from the sessions... the number did not change.
