### ISSUE TITLE
Use go-git

### ISSUE THREAD

**Issue by aymanbagabas** [charmbracelet/wish#7]
We could use go-git to implement our git middleware instead of using `git-upload-pack` and `git-receive-pack` cli. This would also handle all the necessary security a git server would have.

Implement https://pkg.go.dev/github.com/go-git/go-git/v5@v5.4.2/plumbing/transport#Session and https://pkg.go.dev/github.com/go-git/go-git/v5@v5.4.2/plumbing/protocol/packp protocols

**Comment by bashbunni** [comment]
@caarlos0 can I close this issue? Looks like you merged the changes in Jan
