### ISSUE TITLE
undefined: wish.Session

### ISSUE THREAD

**Issue by dvdksn** [charmbracelet/wish#96]
I was trying to run a couple of the examples in this repo, but seems they are broken after a recent refactor (`ssh.Session` => `wish.Session`)

```
./main.go:71:28: undefined: wish.Session
```

**Comment by bashbunni** [comment]
Hey @dvdksn I'm not able to reproduce this. What version are you on? What example are you trying to run and how are you running it?

**Comment by dvdksn** [comment]
hey @bashbunni, the problem appears when you try running the examples on their own. It works for me too when I try running them from within this repo. Created a small repo for reference: https://github.com/dvdksn/wish-example

**Comment by 1984gobrr** [comment]
Hi @dvdksn

I had the same issue.

You can fix it by getting the latest changes `go get github.com/charmbracelet/wish@HEAD`

The `wish.Session` type is [new](https://github.com/charmbracelet/wish/blob/f7f0c95e872b6c308ed46d2a14be8b17ec4c889e/types.go#L60) and not present in the latest release.

**Comment by caarlos0** [comment]
@dvdksn if you want to use the types from the main branch you need to use the `@HEAD` version as @1984gobrr pointed out.

if you clone this repo and run the examples, they should work... is that also not working?

**Comment by dvdksn** [comment]
Hey, yes it works when running in this repo, or with @HEAD :-) Thanks all.
